package fit.iuh.cnm_project_be.notification.enums;

public enum NotificationPolicyDenyReason {
    SELF_NOTIFICATION,
    RECIPIENT_NOT_FOUND,
    ACTOR_BLOCKED_RECIPIENT,
    RECIPIENT_BLOCKED_ACTOR,
    NOT_CONVERSATION_MEMBER,
    CONVERSATION_MUTED,
    NOTIFICATION_LEVEL_NONE,
    MENTIONS_ONLY_NOT_MATCHED,
    GLOBAL_NOTIFICATIONS_DISABLED,
    GLOBAL_CHAT_NOTIFICATIONS_DISABLED,
    GLOBAL_CALL_NOTIFICATIONS_DISABLED,
    GLOBAL_SOCIAL_NOTIFICATIONS_DISABLED,
    PUSH_DISABLED,
    PREVIEW_DISABLED,
    UNKNOWN
}
