package fit.iuh.cnm_project_be.notification.enums;

public enum NotificationType {
    NEW_PRIVATE_MESSAGE,
    NEW_GROUP_MESSAGE,
    GROUP_MENTION,
    REPLY_TO_MY_MESSAGE,
    REACTION_TO_MY_MESSAGE,

    INCOMING_PRIVATE_CALL,
    MISSED_PRIVATE_CALL,
    GROUP_CALL_STARTED,
    MISSED_GROUP_CALL,

    GROUP_RENAMED,
    GROUP_AVATAR_CHANGED,
    GROUP_BACKGROUND_CHANGED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_NICKNAME_CHANGED,
    GROUP_ADMIN_PROMOTED,
    GROUP_ADMIN_DEMOTED,
    GROUP_OWNER_TRANSFERRED,
    GROUP_LEFT,
    GROUP_DISBANDED,

    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    POST_REACTION,
    POST_COMMENT,
    COMMENT_REPLY,
    COMMENT_MENTION,
    POST_TAGGED,
    POST_SHARED,

    REMINDER_CREATED,
    REMINDER_DUE,
    REMINDER_UPDATED,
    REMINDER_CANCELLED,

    SYSTEM_NOTICE
}
