package fit.iuh.cnm_project_be.realtime.dto;

public enum RealtimeEventType {
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    MESSAGE_REACTION_UPDATED,
    MESSAGE_STATUS_UPDATED,
    MESSAGE_DELIVERY_UPDATED,
    MESSAGE_READ_RECEIPT_UPDATED,
    TYPING_UPDATED,
    CONVERSATION_UPDATED,
    ADMIN_DASHBOARD_UPDATED,
    ADMIN_REPORT_CREATED,
    ADMIN_REPORT_RESOLVED,
    ADMIN_USER_MODERATED
}
