package fit.iuh.cnm_project_be.realtime.dto;

public enum RealtimeEventType {
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    MESSAGE_REACTION_UPDATED,
    MESSAGE_STATUS_UPDATED,
    TYPING_UPDATED,
    CONVERSATION_UPDATED,
    FRIEND_REQUEST_CREATED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    FRIENDSHIP_REMOVED
}
