package fit.iuh.cnm_project_be.message.repository;

import fit.iuh.cnm_project_be.message.entity.Message;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.boot.jdbc.test.autoconfigure.AutoConfigureTestDatabase;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.data.domain.PageRequest;

import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.docker.compose.enabled=false"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.ANY)
class MessageStateRepositoryTest {

    private static final AtomicLong MESSAGE_IDS = new AtomicLong(1L);

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private MessageRepository messageRepository;

    @Autowired
    private MessageUserStateRepository messageUserStateRepository;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("""
                create table if not exists messages (
                    id bigint generated by default as identity primary key,
                    conversation_id uuid not null,
                    sender_id uuid not null,
                    content text,
                    message_type varchar(20) not null,
                    reply_to bigint,
                    reply_to_sender_id uuid,
                    reply_to_content_preview text,
                    reply_to_type varchar(20),
                    created_at timestamp with time zone not null,
                    updated_at timestamp with time zone,
                    deleted_at timestamp with time zone,
                    edited_at timestamp with time zone
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists message_user_states (
                    id bigint generated by default as identity primary key,
                    message_id bigint not null,
                    user_id uuid not null,
                    seen_at timestamp with time zone,
                    hidden_at timestamp with time zone,
                    deleted_for_me_at timestamp with time zone,
                    created_at timestamp with time zone not null,
                    updated_at timestamp with time zone not null,
                    constraint uk_message_user_states_message_user unique (message_id, user_id)
                )
                """);
        jdbcTemplate.execute("delete from message_user_states");
        jdbcTemplate.execute("delete from messages");
    }

    @Test
    void hideForMeExcludesMessageFromVisibleMessages() {
        UUID conversationId = UUID.randomUUID();
        UUID userId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();

        long hiddenMessageId = insertMessage(conversationId, senderId, "hidden", Instant.parse("2026-03-23T01:00:00Z"));
        long visibleMessageId = insertMessage(conversationId, senderId, "visible", Instant.parse("2026-03-23T00:00:00Z"));

        insertState(hiddenMessageId, userId, null, Instant.now(), null);
        insertState(visibleMessageId, userId, null, null, null);

        List<Message> visibleMessages = messageRepository.findVisibleMessages(conversationId, userId, null, null, PageRequest.of(0, 10));

        assertThat(visibleMessages).extracting(Message::getId).containsExactly(visibleMessageId);
    }

    @Test
    void removeForMeExcludesMessageFromListUnreadCountAndPreview() {
        UUID conversationId = UUID.randomUUID();
        UUID userId = UUID.randomUUID();
        UUID senderId = UUID.randomUUID();

        long removedMessageId = insertMessage(conversationId, senderId, "removed", Instant.parse("2026-03-23T02:00:00Z"));
        long visibleMessageId = insertMessage(conversationId, senderId, "visible", Instant.parse("2026-03-23T01:00:00Z"));

        insertState(removedMessageId, userId, null, null, Instant.now());
        insertState(visibleMessageId, userId, null, null, null);

        List<Message> visibleMessages = messageRepository.findVisibleMessages(conversationId, userId, null, null, PageRequest.of(0, 10));
        long unreadCount = messageUserStateRepository.countUnreadMessages(conversationId, userId);
        List<Message> previewMessages = messageRepository.findVisibleMessages(conversationId, userId, null, null, PageRequest.of(0, 1));

        assertThat(visibleMessages).extracting(Message::getId).containsExactly(visibleMessageId);
        assertThat(unreadCount).isEqualTo(1);
        assertThat(previewMessages).extracting(Message::getId).containsExactly(visibleMessageId);
    }

    private long insertMessage(UUID conversationId, UUID senderId, String content, Instant createdAt) {
        long id = MESSAGE_IDS.getAndIncrement();
        jdbcTemplate.update("""
                insert into messages (
                    id, conversation_id, sender_id, content, message_type, created_at
                ) values (?, ?, ?, ?, 'text', ?)
                """, id, conversationId, senderId, content, createdAt);
        return id;
    }

    private void insertState(Long messageId, UUID userId, Instant seenAt, Instant hiddenAt, Instant deletedForMeAt) {
        jdbcTemplate.update("""
                insert into message_user_states (
                    message_id, user_id, seen_at, hidden_at, deleted_for_me_at, created_at, updated_at
                ) values (?, ?, ?, ?, ?, ?, ?)
                """,
                messageId,
                userId,
                seenAt,
                hiddenAt,
                deletedForMeAt,
                Instant.now(),
                Instant.now());
    }
}
