ALTER TABLE moments
    ADD COLUMN IF NOT EXISTS audio_mode VARCHAR(20) NOT NULL DEFAULT 'NONE',
    ADD COLUMN IF NOT EXISTS music_track_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS music_title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS music_artist VARCHAR(255),
    ADD COLUMN IF NOT EXISTS music_url TEXT,
    ADD COLUMN IF NOT EXISTS music_start_seconds INTEGER NOT NULL DEFAULT 0;

